DROP TABLE IF EXISTS `sb_score`;
CREATE TABLE `sb_score` (
	id BIGINT (20) NOT NULL,
	user_id BIGINT (20) NOT NULL,
	type VARCHAR (50) NOT NULL COMMENT '类型',
	score BIGINT(20) NOT NULL COMMENT '积分',
	update_time DATETIME NULL COMMENT '最近更新时间',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8;

DROP TABLE IF EXISTS `sb_score_rank`;
CREATE TABLE `sb_score_rank` (
	id BIGINT (20) NOT NULL,
	user_id BIGINT (20) NOT NULL,
	total_score VARCHAR(50) DEFAULT NULL COMMENT '总积分',
	rank VARCHAR(50) DEFAULT NULL COMMENT '排名',
	beat_rate VARCHAR(50) DEFAULT NULL NULL COMMENT '击败率',
	PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = UTF8;

